# Generated by Django 4.1.3 on 2022-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_type_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_new',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Jahon', 'Jahon'), ('Fan_texnika', 'Fan_texnika')], max_length=20),
        ),
    ]
